---
- name: Install packages
  apt:
    package:
      - libssl-dev
      - python3-flask
      - python3-requests
      - python3-pip
      - python3-sqlalchemy
      - uwsgi
      - uwsgi-plugin-python3
      - oidentd # For postgres into pip

- name: Install python ucam webauth
  pip:
    name: python-ucam-webauth

- name: Copy ucam_webauth keys
  copy:
    src: keys/
    dest: /etc/ucam_webauth_keys/
    owner: root
    group: root
    mode: '0644'
    directory_mode: '0755'

- name: Install hydra_session library
  template:
    src: hydra_session.py
    dest: /usr/local/lib/python3.8/dist-packages/
    owner: root
    group: root
    mode: '0644'
  notify: restart uwsgi

- name: Install oauth_flow
  copy:
    src: oauth_flow/
    dest: /usr/local/lib/python3.8/dist-packages/oauth_flow/
    owner: root
    group: root
    mode: '0644'
    directory_mode: '0755'
  notify: restart uwsgi

- name: Install uwsgi config
  template:
    src: oauth_flow.ini
    dest: /etc/uwsgi/apps-available/oauth_flow.ini
    owner: root
    group: root
    mode: '0640'
  notify: restart uwsgi

- name: Enable uwsgi config
  file:
    src: /etc/uwsgi/apps-available/oauth_flow.ini
    dest: /etc/uwsgi/apps-enabled/oauth_flow.ini
    owner: root
    group: root
    state: link

- name: Enable oidentd
  systemd:
    enabled: true
    state: started
    name: oidentd

- name: Enable uwsgi
  systemd:
    enabled: true
    name: uwsgi
    state: started
