---
- name: Install nginx
  apt:
    package:
      - nginx-full

- name: Disable default nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  register: default

- name: Copy auth nginx config
  template:
    src: auth.conf
    dest: /etc/nginx/sites-available/auth.conf
    owner: root
    group: root
    mode: '0644'
  register: auth

- name: Enable auth nginx config
  file:
    src: /etc/nginx/sites-available/auth.conf
    dest: /etc/nginx/sites-enabled/auth.conf
    owner: root
    group: root
    state: link

- name: Copy control_api nginx config
  template:
    src: control_api.conf
    dest: /etc/nginx/sites-available/control_api.conf
    owner: root
    group: root
    mode: '0644'
  register: control_api

- name: Enable control_api nginx config
  file:
    src: /etc/nginx/sites-available/control_api.conf
    dest: /etc/nginx/sites-enabled/control_api.conf
    owner: root
    group: root
    state: link

- name: Validate nginx config
  command: nginx -t
  changed_when: false

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
  when: default.changed or auth.changed or control_api.changed

- name: Enable nginx
  systemd:
    enabled: true
    name: nginx
    state: started
