---
- name: Install certbot
  hosts: oauth
  become: yes
  become_user: root
  tags:
    - nginx
  vars_files:
    - vars.yaml
  roles:
    - certbot

- name: Install nginx
  hosts: oauth
  become: yes
  become_user: root
  tags:
    - nginx
  vars_files:
    - vars.yaml
  roles:
    - nginx

- name: Install ufw
  hosts: oauth
  become: yes
  become_user: root
  tags:
    - ufw
  vars_files:
    - vars.yaml
  roles:
    - ufw

- name: Install hydra
  hosts: oauth
  become: yes
  become_user: root
  tags:
    - hydra
  vars_files:
    - vars.yaml

  roles:
    - hydra

- name: Install flow
  hosts: oauth
  become: yes
  become_user: root
  tags:
    - flow
  vars_files:
    - vars.yaml
  roles:
    - flow
