log:
  level: panic

serve:
  tls:
    allow_termination_from:
      - 127.0.0.1/32

dsn: postgres:///hydra

urls:
  self:
    issuer: https://{{ server_address }}/

  login: https://{{ server_address }}/login
  consent: https://{{ server_address }}/consent
  error: https://{{ server_address }}/error

webfinger:
  oidc_discovery:
    supported_claims:
      - name
      - family_name
      - given_name
      - preferred_username
      - username
      - email
      - email_verified
      - groups
    supported_scope:
      - email
      - profile
      - groups

secrets:
  system:
    - {{ hydra_system_secret }}
  cookie:
    - {{ hydra_cookie_secret }}
