---
- name: Install certbot
  apt:
    package:
      - nginx-full
      - certbot
      - python3-certbot-nginx

- name: Run certbot
  command: certbot -n --nginx -d {{ server_address }} -m {{ letsencrypt_email }} certonly
  register: certbot
  changed_when: '"no action taken" not in certbot.stdout'
