---
# TODO: setup NIS
- name: Install tmpfile to create /run/hydra/
  copy:
    src: hydra-run.conf
    dest: /etc/tmpfiles.d
    owner: root
    group: root
    mode: '0644'

- name: Create /run/hydra/
  file:
    path: /run/hydra
    state: directory
    owner: hydra
    group: hydra
    mode: '0770'

- name: Copy hydra config
  template:
    src: hydra.yaml
    dest: /home/hydra/.hydra.yaml
    owner: hydra
    group: nogroup
    mode: '0600'
  notify: restart hydra

- name: Copy hydra binary
  copy:
    src: hydra
    dest: /usr/local/bin/hydra
    owner: root
    group: root
    mode: '0755'
  register: binary
  notify: restart hydra

- name: Install postgres
  apt:
    package:
      - postgresql
      - python3-psycopg2 # For ansible to modify postgres

- name: Install acl # Makes sudo -u postgres work
  apt:
    package:
      - acl

- name: Create hydra postgres user
  become: true
  become_user: postgres
  postgresql_user:
    name: hydra

- name: Create hydra postgres database
  become: true
  become_user: postgres
  postgresql_db:
    name: hydra

- name: Enable postgres
  systemd:
    enabled: true
    name: postgresql

- name: Migrate sql
  become: true
  become_user: hydra
  command: hydra migrate sql -y postgres:///hydra
  when: binary.changed

- name: Copy hydra systemd service
  copy:
    src: hydra.service
    dest: /usr/local/lib/systemd/system/
    owner: root
    group: root
    mode: '0644'
  notify: restart hydra
  register: systemd

- name: Reload daemon
  systemd:
    name: hydra
    daemon_reload: true
  when: systemd.changed

- name: Start hydra
  systemd:
    enabled: true
    name: hydra
    state: started

- name: Copy client creation script
  copy:
    src: oauth-new-client
    dest: /usr/local/sbin/
    owner: root
    group: root
    mode: '0755'
