---
# TODO: setup NIS
- name: Install tmpfile to create /run/hydra/
  copy:
    src: hydra-run.conf
    dest: /etc/tmpfiles.d
    owner: root
    group: root
    mode: '0644'

- name: Create /run/hydra/
  file:
    path: /run/hydra
    state: directory
    owner: hydra
    group: hydra
    mode: '0770'

- name: Copy hydra config
  template:
    src: hydra.yaml
    dest: /home/hydra/.hydra.yaml
    owner: hydra
    group: nogroup
    mode: '0600'
  notify: restart hydra

- name: Check if hydra is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/hydra
  register: existing_binary

- name: Take database backup of existing installation
  when: existing_binary.stat.exists
  block:
  - name: create blank dump destination
    ansible.builtin.file:
      dest: "/var/backups/hydra-db-{{ ansible_date_time.iso8601_basic_short }}"
      state: touch
      owner: postgres
      group: hydra-admin
      mode: '0640'
  - name: run pg_dump
    ansible.builtin.command:
      cmd: "pg_dump --file /var/backups/hydra-db-{{ ansible_date_time.iso8601_basic_short }} --format=custom hydra"
    become_user: postgres
    register: db_backup

- name: Copy hydra binary
  unarchive:
    src: "https://github.com/ory/hydra/releases/download/v{{ hydra_version }}/hydra_{{ hydra_version }}-linux_64bit.tar.gz"
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: '0755'
    remote_src: true
    extra_opts:
      - hydra # This specifies the file to extract
  register: binary
  notify: restart hydra

- name: Install postgres
  apt:
    package:
      - postgresql
      - python3-psycopg2 # For ansible to modify postgres

- name: Install acl # Makes sudo -u postgres work
  apt:
    package:
      - acl

- name: Create hydra postgres user
  become: true
  become_user: postgres
  postgresql_user:
    name: hydra

- name: Create hydra postgres database
  become: true
  become_user: postgres
  postgresql_db:
    name: hydra

- name: Enable postgres
  systemd:
    enabled: true
    name: postgresql

- name: Migrate sql
  become: true
  become_user: hydra
  command: hydra migrate sql -y postgres:///hydra
  when: binary.changed

- name: Copy hydra systemd service
  copy:
    src: hydra.service
    dest: /usr/local/lib/systemd/system/
    owner: root
    group: root
    mode: '0644'
  notify: restart hydra
  register: systemd

- name: Reload daemon
  systemd:
    name: hydra
    daemon_reload: true
  when: systemd.changed

- name: Start hydra
  systemd:
    enabled: true
    name: hydra
    state: started

- name: Copy client creation script
  copy:
    src: oauth-new-client
    dest: /usr/local/sbin/
    owner: root
    group: root
    mode: '0755'
